# Generated by Django 2.2.2 on 2019-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(max_length=3)),
                ('alerta', models.IntegerField()),
                ('humidade_ar', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('humidade_solo', models.IntegerField()),
                ('presenca_agua', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('dataleitura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
